### ISSUE TITLE
Fix automatic episode numbering in the sidebar

### ISSUE THREAD

**Issue by anenadic** [carpentries-incubator/python-intermediate-development#411] opened 2024-12-06 14:43 UTC
After support for this is enabled in the new release of sandpaper is made available (expected to be 0.16.11)

**Comment by bielsnohr** [comment] 2024-12-06 17:56
Duplicate of #409 :wink: I'll add the version information to that issue. Closing.

**Closed by bielsnohr** 2024-12-06 17:56 UTC
